### ISSUE TITLE
Where do I put the code

### ISSUE THREAD

**Issue by pokemon2308** [kgsensei/NitroType-AutoTyper#1]

**Comment by kgsensei** [comment]
It shouldn't matter too much. Just anywhere that's easy to access I guess.

On some of my previous projects the webdriver has been out of date so if that's an issue as well you can get the latest one from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

If I were you I would put the files on my desktop or documents folder.

**Comment by pokemon2308** [comment]
Ok thanks, I think this doesn't work on a chromebook though

**Comment by kgsensei** [comment]
I'm unsure of how to make this work on a chromebook though I think its possible.
There is a different driver for chrome that you would have to use to run it through the chrome browser. I don't use chrome though. You would also want a little bit of experience already because the file is built for edge mostly. You would need to know how to change that.
